name: Deploy Back to Coolify

on:
  push:
    branches:
      - main
    paths:
      - "back/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Coolify Deployment WebHook
        run: |
          curl -v --fail --show-error -X POST \
            --header 'Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}' \
            "${{ secrets.COOLIFY_BACK_DEPLOY_HOOK }}"
