name: Deploy Back to Coolify

on:
  push:
    branches:
      - main
    paths:
      - "back/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Coolify Deployment WebHook
        run: |
          curl --fail --show-error -X POST "${{ secrets.COOLIFY_BACK_DEPLOY_HOOK }}"
